### ISSUE TITLE
The model parameter file may be corrupted or incorrectly formatted

### ISSUE THREAD

**Issue by yihonghui** [SinMDM/SinMDM#5]
Hi author, when I was testing the humanml and mixamo datasets, the following problems occurred when loading the model

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/SinMDM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/SinMDM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/build/SinMDM/sample/generate.py", line 295, in <module>
    main()
  File "/home/ubuntu/build/SinMDM/sample/generate.py", line 91, in main
    state_dict = torch.load(args.model_path, map_location='cpu')
  File "/home/ubuntu/anaconda3/envs/SinMDM/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/SinMDM/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.

How should I handle this situation

**Comment by DJTaichi** [comment]
I believe this is due to the fact that you are specifying a json file when executing the program.
If you specify a ".pt" file as an argument, I think you will be able to execute the program successfully.
